rouge: true
permalink: /:title.html

title : William E. Byrd's Blog
tagline: webyrd
author :
  name : William E. Byrd
  email : webyrd@gmail.com
  github : webyrd

production_url : http://webyrd.metareflection.club

markdown: kramdown
